version: 2
updates:
  # Maintain dependencies for Core
  - package-ecosystem: "gomod"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/core"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # Maintain dependencies for Core Dockerfiles
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/core"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # Maintain dependencies for JS-SDK
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/sdk/js"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
