version: "3"

services:
  db:
    container_name: flagbase-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: flagbase
      POSTGRES_USER: flagbase
      POSTGRES_PASSWORD: BjrvWmjQ3dykPu
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrations:
    container_name: flagbase-migrations
    image: migrate/migrate
    entrypoint: ["/bin/sh"]
    command: ["/scripts/wait-for.sh", "db:5432", "--", "./migrate", "-path", "/migrations", "-database",  "postgres://flagbase:BjrvWmjQ3dykPu@db:5432/flagbase?sslmode=disable", "up"]
    volumes:
      - ./scripts/wait-for.sh:/scripts/wait-for.sh
      - ./migrations:/migrations
    depends_on:
      - db
    links:
      - db

  core:
    container_name: flagbase-core
    build: .
    command: ["air"]
    ports:
      - 5051:5051
    volumes:
      - ./:/go/src/github.com/flagbase/flagbase/core
    depends_on:
      - db
      - migrations
    links:
      - db
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro



volumes:
  pgdata:
