name: flagbase-core

on:
  push:
    paths:
      - 'core/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'core/**'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --issues-exit-code=0

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./cmd/flagbased
      working-directory: ./core

    - name: Test
      run: go test  ./... -v -covermode=count -coverprofile=coverage.txt
      working-directory: ./core

    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CORE_CODECOV_TOKEN }}
        file: ./core/coverage.txt
