name: release-flagbase-www-prod

on:
  push:
    branches:
      - release
    paths:
      - 'www/**'

jobs:
  release:
    name: Release website
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.FLAGBASE_COM_ACCESS_TOKEN }}
          event-type: release-website-prod
